### ISSUE TITLE
Remove Connect ID and Api Token from code

### ISSUE THREAD

**Issue by daguy666** [jbmfg/cbdReport#1]
Hey cool project, I would suggest removing the api token and connector id from your code. I haven't (and won't) test them to see if they are still valid. 

But if someone was targeting you, they could gain access to your instance of CB pretty quickly. 

```python
import config

backend = "https://api5.conferdeploy.net"
id = "config.CONNECTOR_ID"
key = "config.API_KEY"
headers = {"X-Auth-Token" : "{}/{}".format(key, id)}
```

Alternatively, you could keep the keys on disk and import them from a config file, or some other form of safe handling of those keys. 

Also you may want to rename `id` to something else. Python considers id as a function. 
https://docs.python.org/2/library/functions.html#id

See ya!

**Comment by jbmfg** [comment]
Whoops, not even sure how that file sneaked in, thanks for the heads up!

**Comment by daguy666** [comment]
👍
